### ISSUE TITLE
Wrong grammer

### ISSUE THREAD

**Issue by yooouuri** [yooouuri/PTS4#22]
<img width="289" alt="schermafbeelding 2016-12-14 om 12 18 56" src="https://cloud.githubusercontent.com/assets/12934957/21180102/b43e528c-c1f7-11e6-8a9a-e24e268fbcce.png">

What means "Ale"? No translations?

**Comment by rensphilipsen** [comment]
Hahahhahahahahahhaahahhahahahahhah Mikey is proven belg

**Comment by yooouuri** [comment]
See commit: 9b44657b74237c2846ded7c9cee4be79b45d1304
