### ISSUE TITLE
Weird white border when creating user

### ISSUE THREAD

**Issue by yooouuri** [yooouuri/PTS4#6]
Steps to reproduce:

1. Upload a picture
2. At "Picture type:" Select User
3. Create new user

<img width="1451" alt="schermafbeelding 2016-11-16 om 22 12 47" src="https://cloud.githubusercontent.com/assets/12934957/20366089/eb7cf06e-ac49-11e6-8a7a-09676b2b3bdc.png">

Weird white border at the top:

<img width="1444" alt="schermafbeelding 2016-11-16 om 22 12 54" src="https://cloud.githubusercontent.com/assets/12934957/20366086/eb63f2c6-ac49-11e6-8aba-36122a842bc0.png">

**Comment by rensphilipsen** [comment]
Dit is allemaal van de backend @MikeVoermans

**Comment by yooouuri** [comment]
@rensphilipsen my bad

**Comment by rensphilipsen** [comment]
Is al goed @yooouuri @MikeVoermans vind dat niet erg
