### ISSUE TITLE
Useless search function?

### ISSUE THREAD

**Issue by yooouuri** [yooouuri/PTS4#8]
The search function is does nothing at the filemanager page?

<img width="545" alt="schermafbeelding 2016-11-16 om 22 22 05" src="https://cloud.githubusercontent.com/assets/12934957/20366381/257944e2-ac4b-11e6-82a5-7e20ded9074d.png">

**Comment by rensphilipsen** [comment]
Dit is voor @MikeVoermans

**Comment by rensphilipsen** [comment]
I agree wit (or zwart) with @yooouuri

**Comment by yooouuri** [comment]
@MikeVoermans 

<img width="1328" alt="schermafbeelding 2016-11-22 om 19 06 05" src="https://cloud.githubusercontent.com/assets/12934957/20535835/d1817378-b0e6-11e6-95b0-aee2bf34bf4d.png">

There is still an input field...

**Comment by rensphilipsen** [comment]
Oh my goodness, when is he going to remove it?!?! It's ridiculous!

**Comment by yooouuri** [comment]
@rensphilipsen i hope soon haha.
@MikeVoermans when the issue has been solved, please attach the commit. (and ofc in other issues!)

see:
http://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github

**Comment by MikeVoermans** [comment]
https://github.com/yooouuri/PTS4/commit/86e5ebc26ca00b6fe36b0932313ff676a450cf19

**Comment by rensphilipsen** [comment]
We know enough.
