### ISSUE TITLE
We don't use the menu when you click on role? 

### ISSUE THREAD

**Issue by yooouuri** [yooouuri/PTS4#9]
Remove or change the hardcoded role name?

Do we use the popup menu? Maybe remove it?

<img width="265" alt="schermafbeelding 2016-11-16 om 22 23 50" src="https://cloud.githubusercontent.com/assets/12934957/20366448/7318db5e-ac4b-11e6-8c04-c27c8dc44491.png">

**Comment by rensphilipsen** [comment]
Dit is voor @MikeVoermans

**Comment by rensphilipsen** [comment]
@MikeVoermans maybe remove it Mikey? We only use ze dropdown for ze logout

**Comment by rensphilipsen** [comment]
I ga akkoord with ze @yooouuri mastter
